<Project>
  <PropertyGroup>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>9.0-recommended</AnalysisLevel>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
    <WarningsAsErrors>$(WarningsAsErrors);AD0001;CS8032;CS9057</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' == 'Tolmach'">
    <PackageReference Include="Microsoft.Unity.Analyzers" Version="1.27.0" PrivateAssets="all" />
    <PackageReference Include="Harmonize" Version="1.0.6" PrivateAssets="all" />
  </ItemGroup>
</Project>
